# Generated by Django 5.2.8 on 2025-11-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_token_distance_km_alter_token_token_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("General Medicine", "General Medicine"),
                    ("Cardiology", "Cardiology"),
                    ("Dermatology", "Dermatology"),
                    ("Orthopedics", "Orthopedics"),
                    ("Pediatrics", "Pediatrics"),
                    ("Neurology", "Neurology"),
                    ("ENT", "ENT"),
                ],
                default="General Medicine",
                max_length=100,
            ),
        ),
    ]
