# Generated by Django 5.2.8 on 2025-11-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(max_length=100),
        ),
    ]
