# Generated by Django 5.2.8 on 2025-11-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_doctor_specialization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("General Physician", "General Physician"),
                    ("Cardiologist", "Cardiologist"),
                    ("Dermatologist", "Dermatologist"),
                    ("Pediatrician", "Pediatrician"),
                    ("Neurologist", "Neurologist"),
                    ("Orthopedic", "Orthopedic"),
                ],
                default="General Physician",
                max_length=100,
            ),
        ),
    ]
