# Generated by Django 5.2.8 on 2025-11-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_doctorschedule'),
    ]

    operations = [
    ]
