# Generated by Django 5.2.8 on 2025-11-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20251122_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='arrival_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='consultation_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='predicted_waiting_time',
            field=models.IntegerField(blank=True, help_text='Predicted waiting time in minutes', null=True),
        ),
    ]
