# Generated by Django 5.2.8 on 2025-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_token_arrival_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='afternoon_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='afternoon_time',
            field=models.TimeField(blank=True, help_text='Custom afternoon time', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='evening_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'Food')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='evening_time',
            field=models.TimeField(blank=True, help_text='Custom evening time', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='morning_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='morning_time',
            field=models.TimeField(blank=True, help_text='Custom morning time', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Additional instructions'),
        ),
    ]
