# Generated by Django 5.2.8 on 2025-11-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_prescriptionitem_afternoon_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_type',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night'), ('custom', 'Custom Times')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='afternoon_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='after', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='evening_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='after', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='morning_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='after', max_length=10),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='timing_morning',
            field=models.BooleanField(default=True),
        ),
    ]
