# Generated by Django 5.2.8 on 2025-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_prescriptionitem_timing_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency_per_day',
            field=models.IntegerField(default=1, help_text='Number of times per day'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='night_food',
            field=models.CharField(choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], default='after', max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='night_time',
            field=models.TimeField(blank=True, help_text='Custom night time', null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_1_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_1_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_2_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_2_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_3_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_3_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_4_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_4_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_5_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_5_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_6_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_6_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_7_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_7_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_8_food',
            field=models.CharField(blank=True, choices=[('before', 'Before Food'), ('after', 'After Food'), ('with', 'With Food')], max_length=10),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_8_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='timing_night',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='timing_type',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('N', 'Night'), ('frequency', 'Times Per Day'), ('custom', 'Custom Times')], default='M', max_length=10),
        ),
    ]
