# Generated by Django 5.2.8 on 2025-11-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_prescriptionitem_frequency_per_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('sent_date', models.DateField()),
                ('dose_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='api.prescriptionitem')),
            ],
            options={
                'unique_together': {('prescription', 'reminder_time', 'sent_date')},
            },
        ),
    ]
